Add back button on explanation page and amend styling
googleinterns/step272-2020 pull request #23
Opened 2021-01-08 03:40 UTC by lin8231

2021-01-08 05:18 UTC, roonil-wazlib requested changes

2021-01-08 05:18 UTC, roonil-wazlib commented on portfolio/frontend/src/containers/Explanation/Explanation.module.css
> +	text-decoration: none;
Can you fix indentation here?

2021-01-08 06:01 UTC, leonnemets approved these changes

2021-01-10 01:25 UTC, lin8231 commented on portfolio/frontend/src/containers/Explanation/Explanation.module.css
> +	text-decoration: none;
Fixed

2021-01-10 21:38 UTC, roonil-wazlib approved these changes

2021-01-10 21:38 UTC, merged