Bug fixes in compselect page
googleinterns/step272-2020 pull request #47
Opened 2021-01-26 00:02 UTC by lin8231

* "Select Competition" in header bar wasn't working properly - fixed this 
* Reduced the on hover scaling of competition cards - this is to accomodate for larger screens (hover effect was making cards overlap before). 
Please note that the app is NOT responsive at this stage, it is currently designed for screens of size 1080px and hence will look that size

2021-01-26 03:53 UTC, roonil-wazlib requested changes

2021-01-26 03:53 UTC, roonil-wazlib commented on project/frontend/src/containers/SelectCompetition/SelectCompetition.js
> +          Welp, you have no competitions... D:
Perhaps something a little less Gen Z

2021-01-26 21:02 UTC, lin8231 commented on project/frontend/src/containers/SelectCompetition/SelectCompetition.js
> +          Welp, you have no competitions... D:
Aww, fine.. D:

2021-01-26 21:17 UTC, lin8231 commented on project/frontend/src/containers/SelectCompetition/SelectCompetition.js
> +          Welp, you have no competitions... D:
Degenzfied

2021-01-26 21:19 UTC, roonil-wazlib approved these changes
LGTM

2021-01-27 02:44 UTC, texm approved these changes

2021-01-27 02:45 UTC, merged